name: get-latest-artifact
description: Get latest artifact from specified branch

inputs:
  branch:
    description: Target branch to get artifacts from
    required: true
  platform:
    description: Platform to search artifacts for (e.g., ubuntu-22.04_x86_64)
    required: true
  github-token:
    description: GitHub token for API access
    required: true

outputs:
  run_id:
    description: The workflow run ID
    value: ${{ steps.latest_artifact.outputs.run_id }}
  package_artifact_id:
    description: The package artifact ID
    value: ${{ steps.latest_artifact.outputs.package_artifact_id }}
  env_artifact_id:
    description: The environment artifact ID
    value: ${{ steps.latest_artifact.outputs.env_artifact_id }}

runs:
  using: composite
  steps:
    - name: Get latest artifact from branch
      id: latest_artifact
      shell: bash
      run: |
        echo "Getting latest successful build from ${{ inputs.branch }} branch..."
        
        # 指定されたブランチの最新の成功したワークフローランを取得
        RUN_ID=$(gh run list \
          --branch "${{ inputs.branch }}" \
          --workflow build-workflow \
          --status success \
          --limit 1 \
          --json databaseId \
          --jq '.[0].databaseId')
        
        if [ -z "$RUN_ID" ]; then
          echo "Error: No successful workflow runs found on ${{ inputs.branch }} branch"
          exit 1
        fi
        
        echo "Found successful run: $RUN_ID"
        
        # そのランから対象プラットフォームに関連する artifact を取得
        ARTIFACTS=$(gh api /repos/${{ github.repository }}/actions/runs/${RUN_ID}/artifacts --jq '.artifacts[] | select(.name | contains("${{ inputs.platform }}")) | {id: .id, name: .name}')
        
        # momo パッケージの artifact ID を取得
        PACKAGE_ARTIFACT_ID=$(echo "$ARTIFACTS" | jq -r 'select(.name | contains("momo-")) | .id' | head -1)
        ENV_ARTIFACT_ID=$(echo "$ARTIFACTS" | jq -r 'select(.name | endswith(".env")) | .id' | head -1)
        
        if [ -z "$PACKAGE_ARTIFACT_ID" ] || [ -z "$ENV_ARTIFACT_ID" ]; then
          echo "Error: Required artifacts not found in run $RUN_ID"
          echo "Available artifacts:"
          echo "$ARTIFACTS"
          exit 1
        fi
        
        echo "run_id=${RUN_ID}" >> $GITHUB_OUTPUT
        echo "package_artifact_id=${PACKAGE_ARTIFACT_ID}" >> $GITHUB_OUTPUT
        echo "env_artifact_id=${ENV_ARTIFACT_ID}" >> $GITHUB_OUTPUT
        echo "Found package artifact: $PACKAGE_ARTIFACT_ID, env artifact: $ENV_ARTIFACT_ID"
      env:
        GH_TOKEN: ${{ inputs.github-token }}