name: download-release
description: 'Download and extract momo binary from the GitHub release specified in VERSION file'

inputs:
  platform:
    description: 'Platform name (e.g. ubuntu-24.04_x86_64)'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: true

outputs:
  release-tag:
    description: 'The tag of the downloaded release'
    value: ${{ steps.get_version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Get version from VERSION file
      id: get_version
      run: |
        VERSION=$(cat VERSION | tr -d '\n')
        echo "Version from VERSION file: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      shell: bash
    
    - name: Download momo binary from release
      run: |
        gh release download ${{ steps.get_version.outputs.version }} \
          --pattern "momo-${{ steps.get_version.outputs.version }}_${{ inputs.platform }}.tar.gz" \
          --clobber
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      shell: bash
    
    - name: Extract momo binary
      run: |
        tar -xzf momo-${{ steps.get_version.outputs.version }}_${{ inputs.platform }}.tar.gz
        
        # ビルドディレクトリ構造を再現
        TARGET="${{ inputs.platform }}"
        mkdir -p _build/$TARGET/release
        
        # 展開されたディレクトリ（momo-<version>_<platform>）を momo にリネームして配置
        mv momo-${{ steps.get_version.outputs.version }}_${{ inputs.platform }} _build/$TARGET/release/momo
        chmod +x _build/$TARGET/release/momo/momo
        
        # バージョン確認
        _build/$TARGET/release/momo/momo --version
      shell: bash